### ISSUE TITLE
请教下能支持msvc的libc吗

### ISSUE THREAD

**Issue by heheda123123** [24bit-xjkp/toolchains#10]
现在windows下只支持x86_64-w64-mingw32这种。是否能支持链接msvc的libc呢？
原因是用xmake的时候不少库并不支持mingw，windows平台能用的库更多

我看zig也没有提供msvc的libc。但是rust是提供了的

**Comment by 24bit-xjkp** [comment]
> 现在windows下只支持x86_64-w64-mingw32这种。是否能支持链接msvc的libc呢？ 原因是用xmake的时候不少库并不支持mingw，windows平台能用的库更多
> 
> 我看zig也没有提供msvc的libc。但是rust是提供了的

clang要使用msvc平台需要`--target=x86_64-windows-msvc`选项，然后使用系统安装的Windows SDK，或者你可以从其他项目下载msvc sysroot然后通过`--sysroot`设置sysroot位置。但是你应该先尝试一下使用clang-cl，它提供类似msvc的命令选项。gcc则不支持msvc目标。
