### ISSUE TITLE
windows解压会出现很多关于符号链接的错误

### ISSUE THREAD

**Issue by heheda123123** [24bit-xjkp/toolchains#6]
如图，不知道会不会有影响
![image](https://github.com/user-attachments/assets/75e6e987-a353-4d5f-8524-779ce249e815)

**Comment by 24bit-xjkp** [comment]
> 如图，不知道会不会有影响

这是软链接创建失败了。这是因为Windows下创建软链接需要管理员权限。你可以选择使用管理员权限运行7zip，然后再进行解压。或者你可以开启Windows的开发人员模式，这会在启动进程时给予进程创建软链接的权限，而无需以管理员权限运行。
